### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by kinggigi666** [bit4woo/reCAPTCHA#18]

**Comment by kinggigi666** [comment]
```
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at burp.b0r.a(Unknown Source)
	at burp.b0r.<init>(Unknown Source)
	at burp.c73.a(Unknown Source)
	at burp.igl.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
请问师傅导入报错如何解决

**Comment by dddwill8-day0** [comment]
同

**Comment by dddwill8-day0** [comment]
java.lang.Exception: Extension class is not a recognized type
	at burp.u2d.C(Unknown Source)
	at burp.u2d.<init>(Unknown Source)
	at burp.ic.W(Unknown Source)
	at burp.dx3.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
